import = [
	"~/.config/alacritty/themes/themes/mellow.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "MesloLGLDZ Nerd Font Mono"
size = 14

[keyboard]
bindings = [
  { key = "Left",  mods = "Alt",     chars = "\u001bB"   },
  { key = "Right", mods = "Alt",     chars = "\u001bF"   },
  { key = "Back",  mods = "Command", chars = "\u0015"    },
]

